
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database-types';

const SUPABASE_URL = "https://ucamfuqbgtdjsasnjmbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjYW1mdXFiZ3RkanNhc25qbWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDIwNzAsImV4cCI6MjA1OTAxODA3MH0.LL9Nsl6hP18LRXAkaw3RWsPBwMFcnuZ40KUUnDtm2u4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
